name: fly build test
on:
    push:
        branches:
            - master
            - develop
    workflow_dispatch:
jobs:
    install-python:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: ['3.5', '3.6', '3.7', '3.8', '3.9', '3.10-dev']
                  architecture: 'x64'
            - name: Get Python version
              run: python -V
            - name: Install dependencies
              run: |
                  sudo apt install libssl-dev zlib1g-dev
                  python -m pip install --upgrade pip
                  python -m pip intsall -r requirements.txt
            - name: Make fly library
              run: |
                  ./configure
                  make
                  make install
            - name: Run Python
              run: python -m pytest tests

