name: Test_on_FreeBSD
on:
    push:
        branches:
            - master
            - develop

env:
    LC_ALL: C.UTF-8
    LANG: C.UTF-8
jobs:
    fly-test:
        runs-on: macos-10.15
        strategy:
            max-parallel: 1
            matrix:
                python-version: ['3.6', '3.7', '3.8', '3.9', '3.10-dev']
        steps:
            - uses: actions/checkout@v2
            - name: Setup FreeBSD
              uses: vmactions/freebsd-vm@v0.1.5
              with:
                  usesh: true
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
                  architecture: 'x64'
            - name: Get Python version
              run : python3 -V
            - name: Install dependencies
              run: |
                  sudo pkg update
                  sudo pkg install -y autoconf autoconf-archive automake autotools gcc
                  python3 -m pip install --upgrade pip
                  python3 -m pip install -r requirements.txt
            - name: Make fly library
              run: |
                  autoreconf
                  ./configure
                  cat config.h
                  make
                  make install
            - name: Update resolv conf file
              run: |
                  echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
            - name: Build extension module
              run: |
                  python3 setup.py build
                  cp -rf build/lib.*/fly/_fly_server.cpython* fly/
            - name: Make self certificate for SSL/TLS
              run: |
                  openssl req \
                  -subj '/CN=localhsot' \
                  -x509 -nodes -days 365 -newkey rsa:2048 \
                  -keyout tests/fly_test.key \
                  -out tests/fly_test.crt
            - name: Run Python fly test
              run: python3 -m pytest tests -xv
