name: Test_on_FreeBSD
on:
    push:
        branches:
            - master
            - develop

env:
    LC_ALL: C.UTF-8
    LANG: C.UTF-8
jobs:
    fly-test:
        runs-on: macos-10.15
        steps:
            - uses: actions/checkout@v2
            - name: Setup FreeBSD
              uses: vmactions/freebsd-vm@v0.1.5
              with:
                  usesh: true
                  mem: 4096
                  prepare: |
                      pkg update
                      pkg install -y autoconf autoconf-archive automake autotools gcc sqlite3 python310 py310-sqlite3
                      python3.10 -m ensurepip
                      python3.10 -m pip install --upgrade pip
                  run: |
                      autoreconf
                      ./configure
                      cat config.h
                      make
                      make install
                      echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
                      python3.10 -m pip -r requirements.txt install
                      python3.10 setup.py build
                      cp -rf build/lib.*/fly/_fly_server.cpython* fly/
                      openssl req \
                      -subj '/CN=localhsot' \
                      -x509 -nodes -days 365 -newkey rsa:2048 \
                      -keyout tests/fly_test.key \
                      -out tests/fly_test.crt
                      python3.10 -m pytest tests -xv
