name: Test
on:
    push:
        branches:
            - master
            - develop

env:
    LC_ALL: en_US.UTF-8
    LANG: en_US.UTF-8
jobs:
    fly-test:
        runs-on: [macos-latest]
        continue-on-error: false
        strategy:
            max-parallel: 1
            matrix:
                python-version: ['3.6']
        steps:
        - uses: actions/checkout@v2
        - name: Setup bash
          run: source ~/.bash_profile
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
              python-version: ${{ matrix.python-version }}
        - name: Get Python version
          run: python3 -V
        - name: Homebrew update
          run: brew update
        - name: Install dependencies
          run: |
              brew install openssl zlib brotli
              brew install automake autoconf autoconf-archive
              python3 -m pip install --upgrade pip
              python3 -m pip install -r requirements.txt
        - name: Make fly library
          run: |
              autoreconf --force --install
              ./configure
              cat config.h
              make
              make install
        - name: Update resolv.conf file
          run: |
              echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
              #        - name: Setup tmate session
              #          uses: mxschmitt/action-tmate@v3
        - name: Build extension module
          run: |
              python3 setup.py build
              cp -rf build/lib.*/fly/_fly_* fly/
        - name: Make self certificate for SSL/TLS
          run: |
              openssl req \
              -subj '/CN=localhost' \
              -x509 -nodes -days 365 -newkey rsa:2048 \
              -keyout tests/fly_test.key \
              -out tests/fly_test.crt
              #        - name: Setup tmate session
              #          uses: mxschmitt/action-tmate@v3
        - name: Run Python fly test
          run: python3 -m pytest --force-flaky --max-runs=3 --min-passes=1 tests -xv
